services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nicosebaphp-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.27-alpine
    container_name: nicosebaphp-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
